# Generated by Django 2.2.7 on 2019-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20191120_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='indentificator',
            field=models.FloatField(default=0.0),
        ),
    ]
