# Generated by Django 2.2.7 on 2019-11-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todoitem_indentificator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='indentificator',
        ),
    ]
